import type { Course } from "./types";

export const courses: Course[] = [
  {
    id: "patient-advocacy-101",
    title: "Patient Advocacy 101",
    description: "How to navigate complex medical systems, ask the right questions, and advocate for yourself or a family member.",
    instructor: "Dr. Sarah Levy, Patient Rights Specialist",
    duration: "3h 20min",
    level: "beginner",
    category: "Patient Empowerment",
    enrolled: 2841,
    rating: 4.9,
    language: ["English", "Russian", "Hebrew"],
  },
  {
    id: "understanding-oncology",
    title: "Understanding Your Cancer Diagnosis",
    description: "A guide for patients and families: staging, treatment options, clinical trials, and second opinions.",
    instructor: "Dr. Elena Volkova, Oncologist",
    duration: "5h 10min",
    level: "beginner",
    category: "Oncology",
    enrolled: 1654,
    rating: 4.8,
    language: ["Russian", "English"],
  },
  {
    id: "cardiac-recovery",
    title: "Cardiac Surgery: Recovery & Rehabilitation",
    description: "Evidence-based guide to post-operative recovery, lifestyle adjustments, and long-term heart health.",
    instructor: "Dr. Mikhail Stern, Cardiologist",
    duration: "4h 45min",
    level: "intermediate",
    category: "Cardiology",
    enrolled: 987,
    rating: 4.7,
    language: ["Russian", "Hebrew", "English"],
  },
  {
    id: "rare-disease-guide",
    title: "Living with a Rare Disease",
    description: "Practical strategies for diagnosis, finding specialists, accessing research, and building a care team.",
    instructor: "Dr. Rina Goldberg, Neurologist",
    duration: "6h 00min",
    level: "intermediate",
    category: "Rare Diseases",
    enrolled: 743,
    rating: 5.0,
    language: ["Russian", "Hebrew"],
  },
];
