import type { GlobalDoctor } from "./types";

export const globalDoctors: GlobalDoctor[] = [
  {
    id: "gd-1",
    name: "Prof. Klaus Werner",
    title: "MD, PhD",
    specialty: "Neuro-oncology",
    institution: "Charité Universitätsmedizin Berlin",
    country: "Germany",
    city: "Berlin",
    languages: ["German", "English"],
    hIndex: 42,
    publications: 187,
    verified: true,
  },
  {
    id: "gd-2",
    name: "Dr. Priya Nair",
    title: "MBBS, DM",
    specialty: "Hematology",
    institution: "Tata Memorial Hospital",
    country: "India",
    city: "Mumbai",
    languages: ["English", "Hindi", "Marathi"],
    hIndex: 28,
    publications: 94,
    verified: true,
  },
  {
    id: "gd-3",
    name: "Dr. Jean-Pierre Moreau",
    title: "MD",
    specialty: "Cardiothoracic Surgery",
    institution: "Hôpital Lariboisière",
    country: "France",
    city: "Paris",
    languages: ["French", "English"],
    hIndex: 35,
    publications: 142,
    verified: true,
  },
  {
    id: "gd-4",
    name: "Dr. Amir Cohen",
    title: "MD, MPH",
    specialty: "Rare Diseases",
    institution: "National Institutes of Health",
    country: "USA",
    city: "Bethesda, MD",
    languages: ["English", "Hebrew"],
    hIndex: 51,
    publications: 231,
    verified: true,
  },
  {
    id: "gd-5",
    name: "Prof. Yuki Tanaka",
    title: "MD, PhD",
    specialty: "Immunology",
    institution: "Keio University School of Medicine",
    country: "Japan",
    city: "Tokyo",
    languages: ["Japanese", "English"],
    hIndex: 38,
    publications: 156,
    verified: true,
  },
];
